export const UPLOAD_PIC_SUCCESS = "UPLOAD_PIC_SUCCESS";
export const UPLOAD_PIC_FAILURE = "UPLOAD_PIC_FAILURE";
export const UPLOAD_PIC_LOADING = "UPLOAD_PIC_LOADING";
export const UPLOAD_PIC_PROGRESS = "UPLOAD_PIC_PROGRESS";

export const GET_PIC_SUCCESS = "GET_PIC_SUCCESS";
export const GET_PIC_FAILURE = "GET_PIC_FAILURE";
