export const SET_NEW_COMMENT = "SET_NEW_COMMENT";
export const POST_NEW_COMMENT_LOADING = "POST_NEW_COMMENT_LOADING";
export const POST_NEW_COMMENT_SUCCESS = "POST_NEW_COMMENT_SUCCESS";
export const POST_NEW_COMMENT_FAILURE = "POST_NEW_COMMENT_FAILURE";
